# Generated by Django 4.0.3 on 2022-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_acticles_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.TextField(max_length=120)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
